### ISSUE TITLE
启动后无法连接服务器connect refused getsockopt

### ISSUE THREAD

**Issue by SnubSum31041247** [HIM049/MCDR_HibernateR#11]
>
[MCDR] [22:55:10] [Thread-5/INFO] [hibernate_r]: 倒计时结束，关闭服务器
[MCDR] [22:55:10] [Thread-5/DEBUG]: Removed MCDReforgedFlag MCDReforgedFlag.EXIT_AFTER_STOP
[MCDR] [22:55:10] [Thread-5/DEBUG]: Server state has set to "ServerState.STOPPING"
[MCDR] [22:55:10] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:10] [MainThread/DEBUG]:     Time: 22:55:10; ID: 1432
[MCDR] [22:55:10] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:10] [MainThread/DEBUG]:     Content: Stopping the server
[MCDR] [22:55:10] [MainThread/DEBUG]:     Raw content: [22:55:10] [Server thread/INFO]: Stopping the server
[Server] [22:55:10] [Server thread/INFO]: Stopping the server
[MCDR] [22:55:10] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:10] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:10] [MainThread/DEBUG]:     Time: 22:55:10; ID: 1433
[MCDR] [22:55:10] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:10] [MainThread/DEBUG]:     Content: Stopping server
[MCDR] [22:55:10] [MainThread/DEBUG]:     Raw content: [22:55:10] [Server thread/INFO]: Stopping server
[Server] [22:55:10] [Server thread/INFO]: Stopping server
[MCDR] [22:55:10] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:10] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:10] [MainThread/DEBUG]:     Time: 22:55:10; ID: 1434
[MCDR] [22:55:10] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:10] [MainThread/DEBUG]:     Content: Saving players
[MCDR] [22:55:10] [MainThread/DEBUG]:     Raw content: [22:55:10] [Server thread/INFO]: Saving players
[Server] [22:55:10] [Server thread/INFO]: Saving players
[MCDR] [22:55:10] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:10] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:10] [MainThread/DEBUG]:     Time: 22:55:10; ID: 1435
[MCDR] [22:55:10] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:10] [MainThread/DEBUG]:     Content: Saving worlds
[MCDR] [22:55:10] [MainThread/DEBUG]:     Raw content: [22:55:10] [Server thread/INFO]: Saving worlds
[Server] [22:55:10] [Server thread/INFO]: Saving worlds
[MCDR] [22:55:10] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:10] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:10] [MainThread/DEBUG]:     Time: 22:55:10; ID: 1436
[MCDR] [22:55:10] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:10] [MainThread/DEBUG]:     Content: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:overworld[MCDR] [22:55:10] [MainThread/DEBUG]:     Raw content: [22:55:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:overworld
[Server] [22:55:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:overworld
[MCDR] [22:55:10] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1437
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_nether
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_nether
[Server] [22:55:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_nether
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1438
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_end
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_end
[Server] [22:55:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[永恒的世界]'/minecraft:the_end
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1439
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: ThreadedAnvilChunkStorage (world): All chunks are saved
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1440
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1441
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1442
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: ThreadedAnvilChunkStorage: All dimensions are saved
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [22:55:11] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1443
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: MixinMinecraftServer#onServerStopped()
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: MixinMinecraftServer#onServerStopped()
[Server] [22:55:11] [Server thread/INFO]: MixinMinecraftServer#onServerStopped()
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1444
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Syncmatica#shutdown()
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Syncmatica#shutdown()
[Server] [22:55:11] [Server thread/INFO]: Syncmatica#shutdown()
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1445
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Context#shutdown()
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Context#shutdown()
[Server] [22:55:11] [Server thread/INFO]: Context#shutdown()
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1446
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Context#shutdownServices()
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Context#shutdownServices()
[Server] [22:55:11] [Server thread/INFO]: Context#shutdownServices()
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1447
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Context#unregisterReceivers(): [SERVER] -> unregisterSyncmaticaHandlers
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Context#unregisterReceivers(): [SERVER] -> unregisterSyncmaticaHandlers
[Server] [22:55:11] [Server thread/INFO]: Context#unregisterReceivers(): [SERVER] -> unregisterSyncmaticaHandlers
[MCDR] [22:55:11] [MainThread/DEBUG]: Parsed text from server stdout:
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:11] [MainThread/DEBUG]:     Time: 22:55:11; ID: 1448
[MCDR] [22:55:11] [MainThread/DEBUG]:     Player: None; Source: 0; Logging level: INFO
[MCDR] [22:55:11] [MainThread/DEBUG]:     Content: Syncmatica#deinit()
[MCDR] [22:55:11] [MainThread/DEBUG]:     Raw content: [22:55:11] [Server thread/INFO]: Syncmatica#deinit()
[Server] [22:55:11] [Server thread/INFO]: Syncmatica#deinit()
[MCDR] [22:55:11] [TaskExecutor/DEBUG]: Dispatching MCDREvent[id='mcdr.general_info', default_method_name='on_info'] with args (Info)
[MCDR] [22:55:22] [Thread-5/WARNING] [hibernate_r]: 未找到服务器图标，设置为None
[MCDR] [22:55:22] [Thread-5/INFO] [hibernate_r]: 伪装服务端已启动
[MCDR] [22:55:22] [Thread-5/INFO] [hibernate_r]: 开始监听端口
>
[MCDR] [22:55:59] [Thread-5/INFO] [hibernate_r]: 伪装服务器收到了一次ping: b'\x10\x00\xff\x05\tlocalhostc\xdd\x01'
[MCDR] [22:56:04] [Thread-5/INFO] [hibernate_r]: 伪装服务器收到了一次连接请求: b'\x10\x00\xff\x05\tlocalhostc\xdd\x02'
[MCDR] [22:56:04] [Thread-5/INFO] [hibernate_r]: 启动服务器
[MCDR] [22:56:04] [Thread-5/WARNING]: 服务端不能多次启动

**Comment by SnubSum31041247** [comment]
aaaaa :（

**Comment by HIM049** [comment]
你的日志截止到了伪装服务器接收到了两次进入请求并且准备启动服务器，你可以检查一下在对伪装服务器发送请求后服务器是否被启动。

**Comment by SnubSum31041247** [comment]
没有启动

**Comment by SnubSum31041247** [comment]
未被启动

**Comment by SnubSum31041247** [comment]
[MCDR] [01:04:37] [Thread-14/INFO] [hibernate_r]: 手动唤醒
[MCDR] [01:04:37] [TaskExecutor/DEBUG]: Dispatching MCDREvent(id='mcdr.general_info', default_method_name='on_info') with args [Info(id=1500, hour=1, min=4, sec=37, raw_content='!!hr wakeup', content='!!hr wakeup', source=<InfoSource.CONSOLE: 1>, logging_level=None)]
[MCDR] [01:04:37] [TaskExecutor/DEBUG]: Dispatching MCDREvent(id='mcdr.user_info', default_method_name='on_user_info') with args [Info(id=1500, hour=1, min=4, sec=37, raw_content='!!hr wakeup', content='!!hr wakeup', source=<InfoSource.CONSOLE: 1>, logging_level=None)]
[MCDR] [01:04:43] [Thread-12/WARNING] [hibernate_r]: 未找到服务器图标，设置为None
[MCDR] [01:04:43] [Thread-12/INFO] [hibernate_r]: 伪装服务端已启动
[MCDR] [01:04:43] [Thread-12/INFO] [hibernate_r]: 开始监听端口
[MCDR] [01:04:47] [Thread-14/WARNING]: 服务端不能多次启动

**Comment by SnubSum31041247** [comment]
休眠时进入服务器
MCDR] [01:07:36] [Thread-24/INFO] [hibernate_r]: 伪装服务端已启动
[MCDR] [01:07:36] [Thread-24/INFO] [hibernate_r]: 开始监听端口
[MCDR] [01:07:38] [Thread-24/INFO] [hibernate_r]: 伪装服务器收到了一次连接请求: b'\x10\x00\xff\x05\tlocalhostc\xdd\x02'
[MCDR] [01:07:38] [Thread-24/INFO] [hibernate_r]: 启动服务器
[MCDR] [01:07:38] [Thread-24/WARNING]: 服务端不能多次启动

**Comment by HIM049** [comment]
应该是代码逻辑问题，新版本优化了逻辑，应该解决了
