### ISSUE TITLE
手动睡眠与定时睡眠冲突，导致伪装服务端与主服务端并存，无法进入主服务端

### ISSUE THREAD

**Issue by guoyaoyao2011** [HIM049/MCDR_HibernateR#12]
手动休眠后，第一个伪装服务端启动，主服务端关闭
计时仍在进行，计时结束后将会再次尝试启动另一个伪装服务端，但是因为已经启动一个了，所以一直启动失败，当有玩家唤醒时，主服务端启动，第一个伪装服务端关闭，第二个一直启动失败的伪装服务端启动，所以现在伪装服务端与主服务端并存，而且伪装服务端的优先级应该是高于主服务端的，所以还是无法连接主服务端
![image](https://github.com/user-attachments/assets/61bd348f-8204-4664-ad17-1651133396c3)

**Comment by guoyaoyao2011** [comment]
![image](https://github.com/user-attachments/assets/613c6038-0874-4b1f-bbd7-46bc1ea93916)
![image](https://github.com/user-attachments/assets/9cfc8da2-3404-4483-8f95-31b1d8c06a8c)

**Comment by HIM049** [comment]
已在 32c4dc5 中修复该问题
