### ISSUE TITLE
请问插件的具体休眠影响

### ISSUE THREAD

**Issue by baishabft** [HIM049/MCDR_HibernateR#2]
请问插件是通过何种方式达到休眠的目的呢，我看到并没有直接关闭服务器，这种休眠具体有哪些措施请问awa，有什么弊端吗

**Comment by baishabft** [comment]
例如定时存档插件在休眠过程中还会运行吗

**Comment by HIM049** [comment]
这个一般看 MCDR 的判断，但备份插件在服务器关闭的过程中应该是不会备份的

**Comment by baishabft** [comment]
现在遇到一个问题是，我这边用两个电脑做互通服，一边生存，另一边创造和空岛，用的bc，但是一样的配置，空岛休眠后可以被bc的加入申请激活，而另一个创造服不行

**Comment by HIM049** [comment]
可能是插件配置文件中的监听端口没有填写成和服务器相同的端口，可以检查一下。

**Comment by baishabft** [comment]
检查了，没有问题，而且还发现，在那台有两个服务器的电脑上都装了自动休眠，但是先打开的服务器的自动休眠插件不会工作，后启动的会，换了台电脑测试依旧如此

**Comment by HIM049** [comment]
具体的问题可能需要你提供 MCDR 日志和服务端日志等详细信息才能分析。

插件运作的原理是直接调用 MCDR 的控制函数关闭服务端，然后运行一个监听相同端口的伪装服务器实现的。
