### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Adogs1** [HIM049/MCDR_HibernateR#3]
没有相关的配置文件可供更改
在有玩家时每次启动后一段时间后（测过，和休眠时间一样），也会自动关闭[Bug]

**Comment by HIM049** [comment]
插件配置文件会生成在 MCDR 根目录 /config/HibernateR.json

关于服务器内有玩家也会休眠的情况无法在测试中复现，可以尝试检查一下 online player API 能否正确获取服务器玩家数据

**Comment by wucy777** [comment]
> 插件配置文件会生成在 MCDR 根目录 /config/HibernateR.json
> 
> 关于服务器内有玩家也会休眠的情况无法在测试中复现，可以尝试检查一下 online player API 能否正确获取服务器玩家数据

如果不能应该怎么办

**Comment by HIM049** [comment]
我不了解你服务器的具体情况，但是你可以在 MCDR 配置文件中尝试开启 DEBUG 模式结合日志来排查问题
