### ISSUE TITLE
无法连接到伪装服务器

### ISSUE THREAD

**Issue by Olynx7** [HIM049/MCDR_HibernateR#4]
服务器：Linux 5.15.0-91-generic #101-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
整合包版本：Better MC [Fabric] BMC2 1.20.1

后台伪装服务端运行一段时间之后会关闭套接字，导致无法连接上伪装服务端
![Snipaste_2024-01-24_10-21-03](https://github.com/HIM049/MCDR_HibernateR/assets/41288981/5261c077-0750-4c1e-8b48-fdec9bbd971c)
![image](https://github.com/HIM049/MCDR_HibernateR/assets/41288981/f780947e-5860-4f99-9086-083fb46324be)

**Comment by HIM049** [comment]
请问您使用的是最新版的插件吗？插件在 commit 01470b1 修复过一个类似的错误。
